version: '2'

services:

  csharpauth:
      image: neon-registry.18e7-091a-7bb4-d81e.neoncluster.io/leenet/csharpauth:1.0.82
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
