version: '2'

services:

  csharpauth:
      image: 192.168.1.151:32000/csharpauth:1.0.15
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
