apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: csharpauth
    release-version: "1.2"
  name: csharpauth
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      nodePort: 30767
  selector:
    io.kompose.service: csharpauth
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: csharpauth
    release-version: "1.2"
  name: csharpauth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: csharpauth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: csharpauth
    spec:
      containers:
      - image: 192.168.1.151:32000/csharpauth:1.0.63
        imagePullPolicy: ""
        name: csharpauth
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
